# Start by importing the NumPy library.

In [1]:
import numpy as np

# Create a 2D Array with Sales Data

In [2]:
sales_data = np.zeros((3, 4), dtype=int)
print(sales_data)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Fill the Sales Data with Values

In [3]:
sales_data = np.full((3, 4), [100, 150, 200, 250], dtype=int)
print(sales_data)

[[100 150 200 250]
 [100 150 200 250]
 [100 150 200 250]]


# Reshape the Data Array

In [4]:
reshaped_sales_data = sales_data.reshape(4, 3)
print(reshaped_sales_data)

[[100 150 200]
 [250 100 150]
 [200 250 100]
 [150 200 250]]


#  Generate Random Sales Data

In [5]:
random_sales_data = np.random.randint(50, 300, size=(3, 4))
print(random_sales_data)

[[266 253 114 278]
 [146 128 295 239]
 [208 117 260  87]]


# : Copying and Cloning Data

In [6]:
sales_data_copy = random_sales_data.copy()
sales_data_copy[0, 0] = 999 # Modify the copy
print("Original Sales Data:\n", random_sales_data)
print("Modified Sales Data Copy:\n", sales_data_copy)

Original Sales Data:
 [[266 253 114 278]
 [146 128 295 239]
 [208 117 260  87]]
Modified Sales Data Copy:
 [[999 253 114 278]
 [146 128 295 239]
 [208 117 260  87]]


# Indexing and Slicing 2D Array

In [7]:
sliced_data = random_sales_data[:2, :]
print(sliced_data)

[[266 253 114 278]
 [146 128 295 239]]
