In [1]:
import numpy as np

  # Create a 1D NumPy array with 12 random numbers between 1 and 100

In [2]:
array_1d = np.random.randint(1, 101, size=12)
print("🔢 1D Array:\n", array_1d)

🔢 1D Array:
 [51 50 73 23 99 66 72 49 93 81 27 97]


# 3. Reshape the 1D array into a 2D array (4x3 matrix)

In [3]:
array_2d = array_1d.reshape(4, 3)
print("\n📐 2D Array (4x3 Matrix):\n", array_2d)


📐 2D Array (4x3 Matrix):
 [[51 50 73]
 [23 99 66]
 [72 49 93]
 [81 27 97]]


# 4. Extract and print:

In [4]:
second_row = array_2d[1]
print("\n➡️ Second Row:", second_row)


➡️ Second Row: [23 99 66]


In [5]:
first_column = array_2d[:, 0]
print("⬇️ First Column:", first_column)

⬇️ First Column: [51 23 72 81]


In [6]:
last_two_last_row = array_2d[-1, -2:]
print("🔚 Last Two Elements of Last Row:", last_two_last_row)

🔚 Last Two Elements of Last Row: [27 97]


# 5. Print shape, size, and data type

In [7]:
print("\n🧾 Array Info:")
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data Type:", array_2d.dtype)


🧾 Array Info:
Shape: (4, 3)
Size: 12
Data Type: int32
