In [1]:
import numpy as np


In [2]:
# Coefficient matrix A
A = np.array([[3, 1], [1, 2]])

# Constant matrix b
b = np.array([9, 8])


In [3]:
# Solve the linear system
x = np.linalg.solve(A, b)
print("Solution to the system of equations (x):", x)


Solution to the system of equations (x): [2. 3.]


In [4]:
# Define another matrix B
B = np.array([[1, 2], [3, 4]])

# Matrix multiplication using np.dot()
result_dot = np.dot(A, B)
print("\nMatrix Multiplication using np.dot():\n", result_dot)

# Matrix multiplication using np.matmul()
result_matmul = np.matmul(A, B)
print("\nMatrix Multiplication using np.matmul():\n", result_matmul)



Matrix Multiplication using np.dot():
 [[ 6 10]
 [ 7 10]]

Matrix Multiplication using np.matmul():
 [[ 6 10]
 [ 7 10]]


In [5]:
# Inverse of A
A_inv = np.linalg.inv(A)
print("\nInverse of Matrix A:\n", A_inv)



Inverse of Matrix A:
 [[ 0.4 -0.2]
 [-0.2  0.6]]


In [6]:
# Determinant of A
A_det = np.linalg.det(A)
print("\nDeterminant of Matrix A:", A_det)



Determinant of Matrix A: 5.000000000000001


In [7]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:", eigenvalues)
print("\nEigenvectors of A:\n", eigenvectors)



Eigenvalues of A: [3.61803399 1.38196601]

Eigenvectors of A:
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
