In [1]:
import numpy as np

# Simulated data (3 cities x 7 days)

In [2]:
temperature = np.array([
    [32, 34, 31, 29, 28, 30, 33],  # City 1
    [35, 36, 34, 33, 32, 31, 30],  # City 2
    [27, 28, 29, 31, 30, 32, 33]   # City 3
])

humidity = np.array([
    [60, 55, 58, 62, 65, 63, 59],
    [70, 68, 66, 64, 63, 65, 67],
    [55, 57, 56, 58, 60, 59, 61]
])

wind_speed = np.array([
    [3.4, 2.1, 3.0, 4.0, 2.9, 3.3, 3.5],
    [2.5, 2.7, 2.6, 2.8, 2.9, 3.1, 3.2],
    [3.6, 3.4, 3.3, 3.2, 3.1, 3.0, 2.9]
])


# a. Perceived Temperature = Temperature + Wind Speed

In [3]:
perceived_temp = temperature + wind_speed
print("Perceived Temperature:\n", perceived_temp)

Perceived Temperature:
 [[35.4 36.1 34.  33.  30.9 33.3 36.5]
 [37.5 38.7 36.6 35.8 34.9 34.1 33.2]
 [30.6 31.4 32.3 34.2 33.1 35.  35.9]]


In [4]:
humidity_impact = temperature - humidity
print("Humidity Impact:\n", humidity_impact)

Humidity Impact:
 [[-28 -21 -27 -33 -37 -33 -26]
 [-35 -32 -32 -31 -31 -34 -37]
 [-28 -29 -27 -27 -30 -27 -28]]


In [5]:
threshold_diff = temperature - 30
print("Temperature Difference from 30°C:\n", threshold_diff)


Temperature Difference from 30°C:
 [[ 2  4  1 -1 -2  0  3]
 [ 5  6  4  3  2  1  0]
 [-3 -2 -1  1  0  2  3]]


# ✅ Step 4: Universal Functions (ufunc)

In [6]:
sqrt_wind_speed = np.sqrt(wind_speed)
print("Square Root of Wind Speed:\n", sqrt_wind_speed)

Square Root of Wind Speed:
 [[1.84390889 1.44913767 1.73205081 2.         1.70293864 1.81659021
  1.87082869]
 [1.58113883 1.64316767 1.61245155 1.67332005 1.70293864 1.76068169
  1.78885438]
 [1.8973666  1.84390889 1.81659021 1.78885438 1.76068169 1.73205081
  1.70293864]]


In [7]:
log_humidity = np.log10(humidity)
print("Log10 of Humidity:\n", log_humidity)


Log10 of Humidity:
 [[1.77815125 1.74036269 1.76342799 1.79239169 1.81291336 1.79934055
  1.77085201]
 [1.84509804 1.83250891 1.81954394 1.80617997 1.79934055 1.81291336
  1.8260748 ]
 [1.74036269 1.75587486 1.74818803 1.76342799 1.77815125 1.77085201
  1.78532984]]


In [8]:
seasonal_variation = np.sin(temperature)
print("Seasonal Variation (sin of temperature):\n", seasonal_variation)


Seasonal Variation (sin of temperature):
 [[ 0.55142668  0.52908269 -0.40403765 -0.66363388  0.27090579 -0.98803162
   0.99991186]
 [-0.42818267 -0.99177885  0.52908269  0.99991186  0.55142668 -0.40403765
  -0.98803162]
 [ 0.95637593  0.27090579 -0.66363388 -0.40403765 -0.98803162  0.55142668
   0.99991186]]


# . Mean and Median Temperatures for Each Day

In [9]:
mean_temp_per_day = np.mean(temperature, axis=0)
median_temp_per_day = np.median(temperature, axis=0)

print("Mean Temp per Day:\n", mean_temp_per_day)
print("Median Temp per Day:\n", median_temp_per_day)


Mean Temp per Day:
 [31.33333333 32.66666667 31.33333333 31.         30.         31.
 32.        ]
Median Temp per Day:
 [32. 34. 31. 31. 30. 31. 33.]


In [10]:
max_wind = np.max(wind_speed)
max_wind_index = np.unravel_index(np.argmax(wind_speed), wind_speed.shape)

print("Max Wind Speed:", max_wind)
print("Location of Max Wind Speed (City, Day):", max_wind_index)


Max Wind Speed: 4.0
Location of Max Wind Speed (City, Day): (np.int64(0), np.int64(3))


In [11]:
humidity_variance = np.var(humidity, axis=1)
humidity_std_dev = np.std(humidity, axis=1)

print("Humidity Variance per City:", humidity_variance)
print("Humidity Standard Deviation per City:", humidity_std_dev)


Humidity Variance per City: [9.63265306 4.97959184 4.        ]
Humidity Standard Deviation per City: [3.10365157 2.23149991 2.        ]
