In [1]:
import numpy as np

# Step 1: Create a 3D array representing scientific data
# Shape: (2, 3, 4) -> 2 time points, 3 regions, 4 temperature readings per region
data = np.random.randint(0, 100, (2, 3, 4))
print("Original 3D Array (2 time points, 3 regions, 4 temperature readings):\n", data)

# Step 2: Transpose the 3D array (swap axes to change perspective)
# Changing to: (regions, time points, readings)
transposed_data = np.transpose(data, (1, 0, 2))
print("\nTransposed 3D Array (3 regions, 2 time points, 4 readings):\n", transposed_data)

# Step 3: Swap axes (swap axis 0 and 1: time <-> regions)
swapped_data = np.swapaxes(data, 0, 1)
print("\nSwapped Axes (3 regions, 2 time points, 4 readings):\n", swapped_data)

# Step 4: Slice the 3D array (extract data for the first time point)
first_time_point_data = data[0, :, :]
print("\nData for First Time Point (3 regions, 4 readings):\n", first_time_point_data)


Original 3D Array (2 time points, 3 regions, 4 temperature readings):
 [[[22 94 60 37]
  [40 29 74 42]
  [ 8 26 39 95]]

 [[55 19 47 20]
  [37 92 55 43]
  [65 85 17 96]]]

Transposed 3D Array (3 regions, 2 time points, 4 readings):
 [[[22 94 60 37]
  [55 19 47 20]]

 [[40 29 74 42]
  [37 92 55 43]]

 [[ 8 26 39 95]
  [65 85 17 96]]]

Swapped Axes (3 regions, 2 time points, 4 readings):
 [[[22 94 60 37]
  [55 19 47 20]]

 [[40 29 74 42]
  [37 92 55 43]]

 [[ 8 26 39 95]
  [65 85 17 96]]]

Data for First Time Point (3 regions, 4 readings):
 [[22 94 60 37]
 [40 29 74 42]
 [ 8 26 39 95]]
