# Import NumPy

In [9]:
import numpy as np

# Create an Array of Temperatures Using np.ones()

In [10]:
temperature_data = np.ones((5, 30), dtype=int) * 25
print(temperature_data)

[[25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25
  25 25 25 25 25 25]
 [25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25
  25 25 25 25 25 25]
 [25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25
  25 25 25 25 25 25]
 [25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25
  25 25 25 25 25 25]
 [25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25
  25 25 25 25 25 25]]


# Modify Data Using np.full()

In [11]:
temperature_data = np.full((5, 30), 25)
temperature_data[0] = np.random.randint(20, 35, size=30) # City 1 temperatures
temperature_data[1] = np.random.randint(10, 20, size=30) # City 2 temperatures
print(temperature_data)

[[20 32 20 29 34 20 26 31 31 22 34 21 32 29 24 27 24 28 20 30 33 32 32 34
  31 34 27 22 26 34]
 [11 17 14 18 13 19 13 12 13 13 19 16 10 13 15 19 17 13 18 14 10 11 18 19
  14 12 13 13 18 10]
 [25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25
  25 25 25 25 25 25]
 [25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25
  25 25 25 25 25 25]
 [25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25
  25 25 25 25 25 25]]


# Reshape the Data

In [12]:
temparature_data = np.random.randint(20, 41, size=150)
reshape_temparature_data = temparature_data.reshape(30, 5)
print(reshape_temparature_data)

[[24 34 25 40 22]
 [36 38 27 32 39]
 [28 29 21 26 23]
 [35 20 29 22 20]
 [28 37 28 32 34]
 [28 22 33 20 23]
 [34 31 26 27 26]
 [28 36 34 34 34]
 [23 38 22 34 38]
 [34 27 24 28 40]
 [32 22 26 37 40]
 [39 38 31 26 32]
 [31 20 38 24 35]
 [32 36 24 27 25]
 [36 25 22 32 30]
 [29 28 29 33 38]
 [25 24 22 23 20]
 [21 33 21 26 34]
 [32 27 36 26 20]
 [28 24 28 26 28]
 [27 37 34 22 34]
 [21 40 40 40 28]
 [29 35 36 21 21]
 [25 30 35 35 21]
 [26 39 32 40 26]
 [22 35 27 25 22]
 [38 38 23 28 35]
 [24 35 35 26 20]
 [40 26 25 39 40]
 [30 22 26 38 34]]


# Indexing and Slicing

In [13]:
slicing = reshape_temparature_data[2:6 , :] print(slicing)
print(slicing)

SyntaxError: invalid syntax (168252654.py, line 1)