In [7]:
import numpy as np

In [8]:
np.random.seed(42)

sales_data = np.random.randint(100, 501, size=(5, 12))

print("Sales Data (5 Products x 12 Months):\n", sales_data)

Sales Data (5 Products x 12 Months):
 [[202 448 370 206 171 288 120 202 221 314 430 187]
 [472 199 459 251 230 249 408 357 443 393 485 291]
 [376 260 413 121 352 335 444 148 158 269 287 370]
 [289 274 150 463 154 343 419 230 406 234 120 428]
 [266 373 487 188 415 113 341 364 445 152 485 439]]


 # 2. Element-wise Operations

In [9]:
yearly_sales = np.sum(sales_data, axis=1)
print("\nYearly Sales per Product:\n", yearly_sales)


monthly_growth = np.diff(sales_data, axis=1)
print("\nMonthly Growth per Product:\n", monthly_growth)


Yearly Sales per Product:
 [3159 4237 3533 3510 4068]

Monthly Growth per Product:
 [[ 246  -78 -164  -35  117 -168   82   19   93  116 -243]
 [-273  260 -208  -21   19  159  -51   86  -50   92 -194]
 [-116  153 -292  231  -17  109 -296   10  111   18   83]
 [ -15 -124  313 -309  189   76 -189  176 -172 -114  308]
 [ 107  114 -299  227 -302  228   23   81 -293  333  -46]]


# 10% discount applied (i.e., 90% of original sales)

In [10]:

discounted_sales = sales_data * 0.9
print("\nDiscounted Sales (10% off):\n", discounted_sales)



Discounted Sales (10% off):
 [[181.8 403.2 333.  185.4 153.9 259.2 108.  181.8 198.9 282.6 387.  168.3]
 [424.8 179.1 413.1 225.9 207.  224.1 367.2 321.3 398.7 353.7 436.5 261.9]
 [338.4 234.  371.7 108.9 316.8 301.5 399.6 133.2 142.2 242.1 258.3 333. ]
 [260.1 246.6 135.  416.7 138.6 308.7 377.1 207.  365.4 210.6 108.  385.2]
 [239.4 335.7 438.3 169.2 373.5 101.7 306.9 327.6 400.5 136.8 436.5 395.1]]


In [11]:

exp_growth = np.exp(sales_data / 100)  
print("\nExponential Growth:\n", exp_growth)


log_sales = np.log(sales_data)
print("\nLogarithmic Sales Data:\n", log_sales)


sales_projection = np.power(sales_data, 1.1)
print("\nProjected Sales (1.1x growth):\n", sales_projection)



Exponential Growth:
 [[  7.53832493  88.23467268  40.44730436   7.84596981   5.52896148
   17.81427318   3.32011692   7.53832493   9.11571639  23.10386686
   73.6997937    6.4882964 ]
 [112.16825267   7.31553376  98.49443016  12.30493006   9.97418245
   12.06127612  59.14546985  35.51659315  83.93141691  50.90697767
  127.74038985  18.35679857]
 [ 42.94842598  13.46373804  62.17792293   3.35348465  33.78442846
   28.50273364  84.77494167   4.39294568   4.85495581  14.73167592
   17.6370182   40.44730436]
 [ 17.9933096   15.4869851    4.48168907 102.51406411   4.66459027
   30.87664275  66.02279096   9.97418245  57.97431108  10.38123656
    3.32011692  72.24044001]
 [ 14.2962891   41.67910816 130.3209169    6.55350486  63.4340003
    3.0956565   30.26524426  38.09183673  85.626944     4.5722252
  127.74038985  80.64041898]]

Logarithmic Sales Data:
 [[5.3082677  6.10479323 5.91350301 5.32787617 5.14166356 5.66296048
  4.78749174 5.3082677  5.3981627  5.74939299 6.06378521 5.23110862]
 

In [12]:

mean_sales = np.mean(sales_data)
print("\nMean Sales (Overall):", mean_sales)


variance_per_product = np.var(sales_data, axis=1)
print("\nVariance per Product:\n", variance_per_product)


min_months = np.argmin(sales_data, axis=1)
max_months = np.argmax(sales_data, axis=1)
print("\nMonth of Lowest Sales per Product:", min_months)
print("Month of Highest Sales per Product:", max_months)


std_dev_per_product = np.std(sales_data, axis=1)
print("\nStandard Deviation per Product:\n", std_dev_per_product)



Mean Sales (Overall): 308.45

Variance per Product:
 [10327.6875      9955.90972222 10481.24305556 12982.75
 15516.        ]

Month of Lowest Sales per Product: [ 6  1  3 10  5]
Month of Highest Sales per Product: [ 1 10  6  3  2]

Standard Deviation per Product:
 [101.62523063  99.77930508 102.37794223 113.94187114 124.56323695]
