In [1]:
import numpy as np

# 1. Element-wise Operations
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

# 2. Broadcasting
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([10, 20, 30])
print("\nBroadcasted Addition:\n", A + B)

# 3. ufunc: np.add()
print("\nnp.add:", np.add(a, b), "| Using +:", a + b)

# 4. ufunc: np.subtract()
print("np.subtract:", np.subtract(a, b), "| Using -:", a - b)

# 5. ufunc: np.multiply()
print("np.multiply:", np.multiply(a, b), "| Using *:", a * b)

# 6. ufunc: np.divide() (Avoid divide by zero)
b_safe = b + 1e-6
print("np.divide:", np.divide(a, b_safe), "| Using /:", a / b_safe)

# 7. ufunc: np.mod()
print("np.mod:", np.mod(a, b), "| Using %:", a % b)

# 8. np.exp()
arr_exp = np.array([0, 1, 2])
print("\nnp.exp:", np.exp(arr_exp))

# 9. np.sqrt()
arr_sqrt = np.array([0, 4, 9, 16])
print("np.sqrt:", np.sqrt(arr_sqrt))

# 10. np.log()
arr_log = np.array([1, np.e, np.e**2])
print("np.log:", np.log(arr_log))

# 11. np.log10()
arr_log10 = np.array([1, 10, 100, 1000])
print("np.log10:", np.log10(arr_log10))

# 12. Trigonometric Functions
angles = np.array([0, np.pi/6, np.pi/4, np.pi/2])
print("\nnp.sin:", np.sin(angles))
print("np.cos:", np.cos(angles))
print("np.tan:", np.tan(angles))

# 13. Aggregation Functions
data = np.random.randint(1, 100, size=(4, 5))
print("\n2D Array:\n", data)
print("Sum of all elements:", np.sum(data))
print("Mean of all elements:", np.mean(data))
print("Min in each column:", np.min(data, axis=0))
print("Max in each row:", np.max(data, axis=1))


Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]

Broadcasted Addition:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

np.add: [11 22 33] | Using +: [11 22 33]
np.subtract: [ 9 18 27] | Using -: [ 9 18 27]
np.multiply: [10 40 90] | Using *: [10 40 90]
np.divide: [9.99999    9.999995   9.99999667] | Using /: [9.99999    9.999995   9.99999667]
np.mod: [0 0 0] | Using %: [0 0 0]

np.exp: [1.         2.71828183 7.3890561 ]
np.sqrt: [0. 2. 3. 4.]
np.log: [0. 1. 2.]
np.log10: [0. 1. 2. 3.]

np.sin: [0.         0.5        0.70710678 1.        ]
np.cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 6.12323400e-17]
np.tan: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.63312394e+16]

2D Array:
 [[13  7 68 21 63]
 [21 85 94 86 28]
 [ 3 41 26 76 75]
 [14 18 53  2  6]]
Sum of all elements: 800
Mean of all elements: 40.0
Min in each column: [ 3  7 26  2  6]
Max in each row: [68 94 76 53]
