In [1]:
import numpy as np

# 1. Create a 3x3 matrix filled with zeros

In [2]:
zeros_matrix = np.zeros((3, 3))
print("1️⃣ 3x3 Zeros Matrix:\n", zeros_matrix)

1️⃣ 3x3 Zeros Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 2. Create a 5x5 matrix filled with ones (dtype=float)

In [3]:
ones_matrix = np.ones((5, 5), dtype=float)
print("\n2️⃣ 5x5 Ones Matrix (float):\n", ones_matrix)


2️⃣ 5x5 Ones Matrix (float):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 3. Create a 4x4 matrix filled with the number 7

In [4]:
sevens_matrix = np.full((4, 4), 7)
print("\n3️⃣ 4x4 Matrix of 7s:\n", sevens_matrix)


3️⃣ 4x4 Matrix of 7s:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


# 4. Generate a 4x4 identity matrix

In [5]:
identity_matrix = np.eye(4)
print("\n4️⃣ 4x4 Identity Matrix:\n", identity_matrix)


4️⃣ 4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 5. Create 1D array from 10 to 50 with step 5

In [6]:
step_array = np.arange(10, 51, 5)
print("\n5️⃣ 1D Array (10 to 50, step 5):\n", step_array)


5️⃣ 1D Array (10 to 50, step 5):
 [10 15 20 25 30 35 40 45 50]


# 6. Create 1D array of 100 equally spaced numbers between 0 and 1

In [7]:
linspace_array = np.linspace(0, 1, 100)
print("\n6️⃣ 1D Array of 100 values (0 to 1):\n", linspace_array)


6️⃣ 1D Array of 100 values (0 to 1):
 [0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0

# 7. Generate a 3x3 matrix of random floats (0 to 1)

In [8]:
random_float_matrix = np.random.rand(3, 3)
print("\n7️⃣ 3x3 Random Float Matrix (0 to 1):\n", random_float_matrix)



7️⃣ 3x3 Random Float Matrix (0 to 1):
 [[0.8467123  0.89148302 0.02667919]
 [0.99825384 0.04395141 0.49821961]
 [0.01788637 0.4363889  0.04256645]]


# 8. Generate a 3x3 matrix from standard normal distribution

In [9]:
standard_normal_matrix = np.random.randn(3, 3)
print("\n8️⃣ 3x3 Standard Normal Matrix:\n", standard_normal_matrix)


8️⃣ 3x3 Standard Normal Matrix:
 [[-0.08701649 -1.31433076 -0.17638762]
 [-0.20829081 -0.18572173 -1.78220018]
 [-0.40525149 -1.00726185  0.59414878]]


# 9. Create a 3x3 matrix of random integers (10 to 50)

In [10]:
random_int_matrix = np.random.randint(10, 51, size=(3, 3))
print("\n9️⃣ 3x3 Random Integer Matrix (10 to 50):\n", random_int_matrix)


9️⃣ 3x3 Random Integer Matrix (10 to 50):
 [[29 33 11]
 [38 32 20]
 [39 12 21]]


# 10. Reshape a 1D array of size 12 into a 3x4 matrix

In [11]:
array_1d = np.arange(12)
reshaped_matrix = array_1d.reshape(3, 4)
print("\n🔟 Reshaped 1D Array (3x4):\n", reshaped_matrix)


🔟 Reshaped 1D Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# 11. Flatten a 3x3 matrix using ravel() and flatten()

In [12]:
original_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
raveled = original_matrix.ravel()
flattened = original_matrix.flatten()
print("\n1️⃣1️⃣ Flattened using ravel():", raveled)
print("Flattened using flatten():", flattened)


1️⃣1️⃣ Flattened using ravel(): [1 2 3 4 5 6 7 8 9]
Flattened using flatten(): [1 2 3 4 5 6 7 8 9]


# 12. Clone an array using copy() and verify independence

In [13]:
original_array = np.array([1, 2, 3])
cloned_array = original_array.copy()
original_array[0] = 99
print("\n1️⃣2️⃣ Original after modification:", original_array)
print("Cloned (unchanged):", cloned_array)


1️⃣2️⃣ Original after modification: [99  2  3]
Cloned (unchanged): [1 2 3]


# 13. Slice a 3x3 matrix to extract the second row

In [14]:
matrix_3x3 = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
second_row = matrix_3x3[1]
print("\n1️⃣3️⃣ Second Row of 3x3 Matrix:", second_row)


1️⃣3️⃣ Second Row of 3x3 Matrix: [21 22 23]
