In [19]:
import numpy as np

# Create two random 3x3 matrices
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

# Multiply using np.dot
result_dot = np.dot(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A · B (using np.dot()):\n", result_dot)


Matrix A:
 [[9 4 6]
 [8 9 1]
 [1 9 4]]
Matrix B:
 [[9 3 7]
 [4 6 1]
 [3 2 1]]
A · B (using np.dot()):
 [[115  63  73]
 [111  80  66]
 [ 57  65  20]]


In [20]:
# Multiply using np.matmul
result_matmul = np.matmul(A, B)
print("\nA · B (using np.matmul()):\n", result_matmul)

# Compare with np.dot
print("Are results from dot() and matmul() equal?", np.allclose(result_dot, result_matmul))



A · B (using np.matmul()):
 [[115  63  73]
 [111  80  66]
 [ 57  65  20]]
Are results from dot() and matmul() equal? True


In [21]:
# Create 2x2 matrices
C = np.array([[1, 2], [3, 4]])
D = np.array([[5, 6], [7, 8]])

result_at = C @ D
result_dot_2x2 = np.dot(C, D)

print("\nC @ D:\n", result_at)
print("C · D (np.dot()):\n", result_dot_2x2)
print("Match:", np.allclose(result_at, result_dot_2x2))



C @ D:
 [[19 22]
 [43 50]]
C · D (np.dot()):
 [[19 22]
 [43 50]]
Match: True


In [22]:
# Create 2x2 matrix
E = np.array([[4, 7], [2, 6]])

# Compute inverse
E_inv = np.linalg.inv(E)

# Verify: E · E_inv = Identity
identity_check = np.dot(E, E_inv)

print("\nMatrix E:\n", E)
print("Inverse of E:\n", E_inv)
print("E · E_inv:\n", identity_check)



Matrix E:
 [[4 7]
 [2 6]]
Inverse of E:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
E · E_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [23]:
F = np.array([[2, 5, 3], [1, -2, -1], [1, 3, 4]])
det_F = np.linalg.det(F)
print("\nMatrix F:\n", F)
print("Determinant of F:", det_F)



Matrix F:
 [[ 2  5  3]
 [ 1 -2 -1]
 [ 1  3  4]]
Determinant of F: -20.000000000000007


In [24]:
G = np.array([[4, -2, 1], [1, 1, 0], [0, 5, 4]])
eigenvalues, eigenvectors = np.linalg.eig(G)

print("\nMatrix G:\n", G)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)



Matrix G:
 [[ 4 -2  1]
 [ 1  1  0]
 [ 0  5  4]]
Eigenvalues:
 [2.04791957+1.31124804j 2.04791957-1.31124804j 4.90416086+0.j        ]
Eigenvectors:
 [[-0.554451  -0.17459402j -0.554451  +0.17459402j  0.57055419+0.j        ]
 [-0.28747263+0.19310061j -0.28747263-0.19310061j  0.14614003+0.j        ]
 [ 0.73632374+0.j          0.73632374-0.j          0.80815283+0.j        ]]


In [25]:
A_sys = np.array([[2, 3], [1, 2]])
b_sys = np.array([8, 5])
x = np.linalg.solve(A_sys, b_sys)

print("\nSolving Ax = b")
print("A:\n", A_sys)
print("b:\n", b_sys)
print("x:\n", x)



Solving Ax = b
A:
 [[2 3]
 [1 2]]
b:
 [8 5]
x:
 [1. 2.]


In [26]:
data = np.random.randn(1000)

p25 = np.percentile(data, 25)
p50 = np.percentile(data, 50)
p75 = np.percentile(data, 75)

print("\nPercentiles of random data:")
print("25th:", p25)
print("50th (Median):", p50)
print("75th:", p75)



Percentiles of random data:
25th: -0.6872885076178216
50th (Median): -0.014542708891008367
75th: 0.6473071865648987


In [27]:
import matplotlib.pyplot as plt
data = np.random.randn(1000)
hist, bin_edges = np.histogram(data, bins=20)

print("\nHistogram counts:\n", hist)
print("Bin edges:\n", bin_edges)

# Optional: Visualize
plt.hist(data, bins=20, edgecolor='black')
plt.title("Histogram of Normally Distributed Data")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()


ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
dataset = np.arange(1, 11)

for i in range(1, 4):
    sample = np.random.choice(dataset, size=5, replace=False)
    print(f"\nRandom Sample {i}:", sample)


In [ ]:
normal_data = np.random.randn(1000)
mean = np.mean(normal_data)
std_dev = np.std(normal_data)

print("\nMean of normal distribution:", mean)
print("Standard deviation:", std_dev)


In [ ]:
cumulative_data = np.cumsum(normal_data)

plt.plot(cumulative_data)
plt.title("Cumulative Distribution")
plt.xlabel("Index")
plt.ylabel("Cumulative Sum")
plt.grid(True)
plt.show()


In [ ]:
tosses = np.random.choice([0, 1], size=100)  # 0 = Tails, 1 = Heads
heads = np.sum(tosses)
tails = len(tosses) - heads

print("\nCoin Toss Simulation (100 trials):")
print("Heads:", heads)
print("Tails:", tails)
print("Proportion Heads:", heads / 100)
print("Proportion Tails:", tails / 100)
