In [1]:
import numpy as np

# 1. Create a 5x4 array of zeros to represent grades of 5 students across 4 subjects

In [2]:
grades = np.zeros((5, 4), dtype=int)
print("1️⃣ Initial Grades (All Zeros):\n", grades)

1️⃣ Initial Grades (All Zeros):
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# 2. Fill the array with random grades between 50 and 100

In [3]:
grades = np.random.randint(50, 101, size=(5, 4))
print("\n2️⃣ Random Grades (50-100):\n", grades)


2️⃣ Random Grades (50-100):
 [[80 74 98 58]
 [59 66 79 84]
 [76 73 82 64]
 [63 73 78 80]
 [99 55 77 52]]


# 3. Create a new array for maximum possible grades per subject (assume 100 for all)

In [4]:
max_grades = np.full((1, 4), 100)
print("\n3️⃣ Max Grades per Subject:\n", max_grades)


3️⃣ Max Grades per Subject:
 [[100 100 100 100]]


# 4. Reshape grades array to represent 2 semesters (e.g., 2x10 matrix)

In [5]:
grades_reshaped = grades.reshape(2, 10)
print("\n4️⃣ Reshaped Grades (2 Semesters):\n", grades_reshaped)


4️⃣ Reshaped Grades (2 Semesters):
 [[80 74 98 58 59 66 79 84 76 73]
 [82 64 63 73 78 80 99 55 77 52]]


# 5. Clone the grades array and simulate improvement (e.g., add +5 to each grade)

In [6]:
mproved_grades = grades.copy()
improved_grades += 5
improved_grades = np.clip(improved_grades, 0, 100)  # Ensure no value exceeds 100
print("\n5️⃣ Improved Grades (Cloned and Modified):\n", improved_grades)


NameError: name 'improved_grades' is not defined

# 6. Extract and display:

In [ ]:
#  a. Grades of a specific student (2nd student → index 1)
student_2_grades = grades[1]
# b. Grades in a specific subject (3rd subject → index 2)
subject_3_grades = grades[:, 2]


In [ ]:
print("\n6️⃣ Extracted Data:")
print("Grades of Student 2:", student_2_grades)
print("Grades in Subject 3:", subject_3_grades)