In [1]:
import numpy as np


np.random.seed(0)  
stock_prices = np.random.randint(100, 501, size=(5, 12))  # 5 stocks × 12 months

print("Stock Prices (USD):\n", stock_prices)


percentage_change = np.diff(stock_prices, axis=1) / stock_prices[:, :-1] * 100
print("\nPercentage Change (%):\n", np.round(percentage_change, 2))

row_mean = stock_prices.mean(axis=1, keepdims=True)
normalized_prices = stock_prices - row_mean
print("\nNormalized Prices (Mean Subtracted):\n", np.round(normalized_prices, 2))


volatility = np.sqrt(np.var(stock_prices, axis=1))
print("\nVolatility (Std Dev via sqrt(var)):\n", np.round(volatility, 2))


exp_growth = np.exp(stock_prices / 100)  # scaled to avoid overflow
print("\nExponential Price Growth:\n", np.round(exp_growth, 2))

log_prices = np.log10(stock_prices)
print("\nLog10 of Stock Prices:\n", np.round(log_prices, 2))


mean_prices = np.mean(stock_prices, axis=1)
median_prices = np.median(stock_prices, axis=1)
max_prices = np.max(stock_prices, axis=1)
min_prices = np.min(stock_prices, axis=1)
variance_prices = np.var(stock_prices, axis=1)
std_dev_prices = np.std(stock_prices, axis=1)

print("\nMean Prices per Stock:", np.round(mean_prices, 2))
print("Median Prices per Stock:", np.round(median_prices, 2))
print("Max Prices per Stock:", max_prices)
print("Min Prices per Stock:", min_prices)
print("Variance per Stock:", np.round(variance_prices, 2))
print("Standard Deviation per Stock:", np.round(std_dev_prices, 2))


Stock Prices (USD):
 [[272 147 217 292 423 351 295 459 109 311 377 342]
 [392 187 170 188 496 414 293 139 187 274 188 437]
 [265 125 433 172 365 215 343 297 435 438 199 277]
 [343 385 247 247 498 388 365 285 227 132 131 302]
 [344 251 263 470 283 128 390 228 228 153 489 138]]

Percentage Change (%):
 [[-45.96  47.62  34.56  44.86 -17.02 -15.95  55.59 -76.25 185.32  21.22
   -9.28]
 [-52.3   -9.09  10.59 163.83 -16.53 -29.23 -52.56  34.53  46.52 -31.39
  132.45]
 [-52.83 246.4  -60.28 112.21 -41.1   59.53 -13.41  46.46   0.69 -54.57
   39.2 ]
 [ 12.24 -35.84   0.   101.62 -22.09  -5.93 -21.92 -20.35 -41.85  -0.76
  130.53]
 [-27.03   4.78  78.71 -39.79 -54.77 204.69 -41.54   0.   -32.89 219.61
  -71.78]]

Normalized Prices (Mean Subtracted):
 [[ -27.58 -152.58  -82.58   -7.58  123.42   51.42   -4.58  159.42 -190.58
    11.42   77.42   42.42]
 [ 111.58  -93.42 -110.42  -92.42  215.58  133.58   12.58 -141.42  -93.42
    -6.42  -92.42  156.58]
 [ -32.   -172.    136.   -125.     68.    -82