In [1]:
import numpy as np

# Step 1: Generate random 3x3 coefficient matrix A and 3x1 constant vector b
A = np.random.randint(1, 10, size=(3, 3))
b = np.random.randint(1, 10, size=(3,))

print("Coefficient Matrix A:\n", A)
print("Constant Vector b:\n", b)

# Step 2: Solve the equation A * x = b
x = np.linalg.solve(A, b)

print("\nSolution Vector x:\n", x)

# Step 3: Verify the result by checking if A @ x ≈ b
b_calculated = np.dot(A, x)  # or A @ x

print("\nVerification (A · x):\n", b_calculated)
print("Does A · x ≈ b?", np.allclose(b, b_calculated))  # Should return True


Coefficient Matrix A:
 [[8 6 2]
 [6 1 9]
 [9 9 4]]
Constant Vector b:
 [2 3 1]

Solution Vector x:
 [ 0.65217391 -0.52173913 -0.04347826]

Verification (A · x):
 [2. 3. 1.]
Does A · x ≈ b? True
