In [1]:
import numpy as np

np.random.seed(42)  
scores = np.random.randint(40, 101, size=(10, 5))

print("Exam Scores (10 students x 5 subjects):\n", scores)


Exam Scores (10 students x 5 subjects):
 [[ 78  91  68  54  82]
 [ 47 100  60  78  97]
 [ 58  62  50  50  63]
 [ 92  75  79  63  42]
 [ 61  92  41  63  83]
 [ 69  77  41  99  60]
 [ 72  51  97  61 100]
 [ 83  64  88  66  98]
 [ 81  67  99  55  54]
 [ 86  90  83  94  91]]


In [2]:

total_scores = np.sum(scores, axis=1)


max_score = 100 * scores.shape[1]  # 5 subjects, each out of 100
percentages = total_scores / max_score * 100

print("\nTotal Scores:\n", total_scores)
print("\nPercentages:\n", percentages)



Total Scores:
 [373 382 283 351 340 346 381 399 356 444]

Percentages:
 [74.6 76.4 56.6 70.2 68.  69.2 76.2 79.8 71.2 88.8]


In [3]:
# a. Add a bonus of 5 marks to every score using broadcasting
bonus_scores = scores + 5
bonus_scores = np.clip(bonus_scores, 0, 100)  # Ensuring max remains 100

print("\nScores After Bonus:\n", bonus_scores)



Scores After Bonus:
 [[ 83  96  73  59  87]
 [ 52 100  65  83 100]
 [ 63  67  55  55  68]
 [ 97  80  84  68  47]
 [ 66  97  46  68  88]
 [ 74  82  46 100  65]
 [ 77  56 100  66 100]
 [ 88  69  93  71 100]
 [ 86  72 100  60  59]
 [ 91  95  88  99  96]]


In [4]:
# a. Simulate performance increase using power
performance_boost = np.power(percentages, 1.1)

# b. Logarithmic growth of average score across subjects for each student
avg_scores = np.mean(scores, axis=1)
log_growth = np.log(avg_scores)

print("\nPerformance Boost (percent^1.1):\n", performance_boost)
print("\nLog Growth of Average Scores:\n", log_growth)



Performance Boost (percent^1.1):
 [114.81872243 117.86984012  84.74187604 107.39172623 103.69547468
 105.71015361 117.53046881 123.65257948 109.07569604 139.07666321]

Log Growth of Average Scores:
 [4.31214051 4.3359827  4.03600899 4.25134831 4.21950771 4.23700086
 4.33336146 4.3795235  4.26549282 4.48638665]


In [5]:
# a. Mean and Median score for each subject (column-wise)
subject_means = np.mean(scores, axis=0)
subject_medians = np.median(scores, axis=0)

# b. Best (max) and worst (min) performing student based on total scores
best_score = np.max(total_scores)
worst_score = np.min(total_scores)
best_student = np.argmax(total_scores)
worst_student = np.argmin(total_scores)

print("\nSubject-wise Mean Scores:\n", subject_means)
print("\nSubject-wise Median Scores:\n", subject_medians)
print(f"\nBest Performing Student: Student {best_student} with {best_score} marks")
print(f"Worst Performing Student: Student {worst_student} with {worst_score} marks")



Subject-wise Mean Scores:
 [72.7 76.9 70.6 68.3 77. ]

Subject-wise Median Scores:
 [75.  76.  73.5 63.  82.5]

Best Performing Student: Student 9 with 444 marks
Worst Performing Student: Student 2 with 283 marks
