In [1]:
import numpy as np

# 1. Create a 3x7 array of ones (3 products, 7 days)

In [2]:
sales_data = np.ones((3, 7), dtype=int)
print("1️⃣ Initial Sales Data (All 1s):\n", sales_data)

1️⃣ Initial Sales Data (All 1s):
 [[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


# 2. Modify with realistic random sales data (10 to 50)

In [3]:
sales_data = np.random.randint(10, 51, size=(3, 7))
print("\n2️⃣ Random Sales Data (10 to 50):\n", sales_data)



2️⃣ Random Sales Data (10 to 50):
 [[27 46 27 44 32 49 34]
 [20 21 33 47 21 45 39]
 [24 35 17 48 36 45 33]]


# 3. Generate days of the week (1 to 7) using np.arange and reshape to 3x7 (for demonstration)

In [4]:
days_array = np.tile(np.arange(1, 8), (3, 1))
print("\n3️⃣ Days of the Week (Broadcasted for 3 products):\n", days_array)


3️⃣ Days of the Week (Broadcasted for 3 products):
 [[1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]]


# 4. Flatten the sales data using .ravel() and .flatten()

In [5]:
ravelled = sales_data.ravel()
flattened = sales_data.flatten()
print("\n4️⃣ Flattened Data Comparison:")
print("Using ravel():", ravelled)
print("Using flatten():", flattened)


4️⃣ Flattened Data Comparison:
Using ravel(): [27 46 27 44 32 49 34 20 21 33 47 21 45 39 24 35 17 48 36 45 33]
Using flatten(): [27 46 27 44 32 49 34 20 21 33 47 21 45 39 24 35 17 48 36 45 33]


# 5. Clone sales data and simulate boost in sales (e.g., +10 units during discount)

In [6]:
boosted_sales = sales_data.copy()
boosted_sales += 10
boosted_sales = np.clip(boosted_sales, 0, 100)  # Ensure values stay within logical range
print("\n5️⃣ Boosted Sales After Discount (+10 units):\n", boosted_sales)


5️⃣ Boosted Sales After Discount (+10 units):
 [[37 56 37 54 42 59 44]
 [30 31 43 57 31 55 49]
 [34 45 27 58 46 55 43]]


# 6. Slice to extract sales data for first 3 days (columns 0 to 2)

In [7]:
first_3_days_sales = sales_data[:, :3]
print("\n6️⃣ Sales Data for First 3 Days (All Products):\n", first_3_days_sales)


6️⃣ Sales Data for First 3 Days (All Products):
 [[27 46 27]
 [20 21 33]
 [24 35 17]]
