In [1]:
import numpy as np

arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(10, 20, (3, 4))
vstacked = np.vstack((arr1, arr2))
print("Vertical Stack (6x4):\n", vstacked)


Vertical Stack (6x4):
 [[ 2  3  3  9]
 [ 6  2  9  1]
 [ 8  2  4  1]
 [14 14 12 17]
 [15 15 11 11]
 [17 19 19 16]]


In [2]:
arr3 = np.random.randint(1, 10, (3, 4))
arr4 = np.random.randint(10, 20, (3, 4))
hstacked = np.hstack((arr3, arr4))
print("Horizontal Stack (3x8):\n", hstacked)


Horizontal Stack (3x8):
 [[ 9  9  3  9 18 10 12 13]
 [ 7  6  1  4 14 13 19 17]
 [ 5  5  8  9 14 10 17 15]]


In [3]:
arr5 = np.random.randint(1, 10, (3, 4))
arr6 = np.random.randint(10, 20, (3, 4))
dstacked = np.dstack((arr5, arr6))
print("Stacked along depth (3x4x2):\n", dstacked)


Stacked along depth (3x4x2):
 [[[ 2 17]
  [ 2 16]
  [ 4 10]
  [ 5 13]]

 [[ 1 10]
  [ 3 15]
  [ 7 11]
  [ 3 13]]

 [[ 1 17]
  [ 5 19]
  [ 8 16]
  [ 4 10]]]


In [4]:
arr7 = np.arange(24).reshape(6, 4)
split_equal = np.split(arr7, 2)
print("Split into two (3x4):")
for i, subarr in enumerate(split_equal):
    print(f"Part {i+1}:\n", subarr)


Split into two (3x4):
Part 1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Part 2:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [5]:
arr8 = np.arange(28).reshape(7, 4)
split_three = np.array_split(arr8, 3)
print("Split into three parts:")
for i, subarr in enumerate(split_three):
    print(f"Part {i+1} (shape {subarr.shape}):\n", subarr)


Split into three parts:
Part 1 (shape (3, 4)):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Part 2 (shape (2, 4)):
 [[12 13 14 15]
 [16 17 18 19]]
Part 3 (shape (2, 4)):
 [[20 21 22 23]
 [24 25 26 27]]


In [6]:
arr9 = np.random.randint(1, 10, (2, 3, 4))
transposed_T = arr9.T
print("Original shape:", arr9.shape)
print("Transposed shape with .T:", transposed_T.shape)


Original shape: (2, 3, 4)
Transposed shape with .T: (4, 3, 2)


In [7]:
arr10 = np.random.randint(1, 10, (2, 3, 4))
transposed_axes = np.transpose(arr10, (2, 1, 0))  # (4, 3, 2)
print("Transposed shape with np.transpose():", transposed_axes.shape)


Transposed shape with np.transpose(): (4, 3, 2)


In [8]:
arr11 = np.random.randint(1, 10, (2, 3, 4))
swapped = np.swapaxes(arr11, 0, 2)  # (4, 3, 2)
print("Shape after swapaxes(0,2):", swapped.shape)


Shape after swapaxes(0,2): (4, 3, 2)


In [9]:
arr12 = np.random.randint(1, 10, (5, 3, 4))
slice_2d = arr12[2]  # Get the 3rd element (index 2)
print("Sliced 2D array at index 2:\n", slice_2d)


Sliced 2D array at index 2:
 [[3 5 3 4]
 [8 9 3 7]
 [2 3 6 8]]


In [10]:
arr13 = np.random.randint(1, 10, (3, 4))
arr14 = np.random.randint(10, 20, (3, 2))

# Valid shapes for hstack: same number of rows
try:
    hstack_diff = np.hstack((arr13, arr14))
    print("Horizontally stacked arrays (3x6):\n", hstack_diff)
except ValueError as e:
    print("Error:", e)


Horizontally stacked arrays (3x6):
 [[ 8  5  8  6 14 10]
 [ 2  2  6  7 10 12]
 [ 9  8  8  2 15 17]]


In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([9, 10, 11, 12])
vstack_1d = np.vstack((a, b, c))
print("Stacked 1D arrays (3x4):\n", vstack_1d)


Stacked 1D arrays (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
arr15 = np.random.randint(1, 10, (3, 3))
arr16 = np.random.randint(10, 20, (3, 3))
hstack_2d = np.hstack((arr15, arr16))
print("Horizontally stacked (3x6):\n", hstack_2d)


Horizontally stacked (3x6):
 [[ 2  8  7 13 16 16]
 [ 3  4  1 15 17 14]
 [ 5  8  6 12 17 18]]


In [13]:
arr17 = np.arange(12)
split_parts = np.split(arr17, 4)
print("1D array split into 4 parts:")
for i, part in enumerate(split_parts):
    print(f"Part {i+1}:", part)


1D array split into 4 parts:
Part 1: [0 1 2]
Part 2: [3 4 5]
Part 3: [6 7 8]
Part 4: [ 9 10 11]
