In [1]:
import numpy as np

# 1. Create a 3D array of shape (6 students, 4 terms, 3 subjects)
grades = np.random.randint(50, 101, (6, 4, 3))  # Random grades between 50 and 100

# 2. Vertically stack grades of student 0 and student 1
student0 = grades[0]  # shape (4, 3)
student1 = grades[1]  # shape (4, 3)
vstack_students = np.vstack((student0, student1))  # shape (8, 3)

# 3. Transpose: swap axes to make terms the first axis and students last
transposed_grades = np.transpose(grades, (1, 2, 0))  # shape: (4 terms, 3 subjects, 6 students)

# 4. Split the grades array by subjects
# axis=2 is subjects, so split into 3 parts
subject_splits = np.dsplit(grades, 3)
subjects = ["Math", "Science", "English"]
for i, subject_data in enumerate(subject_splits):
    print(f"{subjects[i]} Grades:\n", subject_data[:, :, 0])  # For display, remove extra dimension

# 5. Swap axes: Swap terms (axis=1) and subjects (axis=2)
swapped_grades = np.swapaxes(grades, 1, 2)  # shape becomes (6, 3, 4)
print("Shape after swapping terms and subjects:", swapped_grades.shape)

# 6. Extract grades for 3rd student (index 2) in Science (subject index 1) for all terms
student3_science_grades = grades[2, :, 1]
print("3rd Student's Science Grades for All Terms:", student3_science_grades)


Math Grades:
 [[84 86 87 86]
 [98 50 84 91]
 [61 86 73 90]
 [66 84 59 86]
 [52 51 78 78]
 [53 60 54 91]]
Science Grades:
 [[ 53  56  91  78]
 [ 71  76  96  60]
 [ 88  80  83  70]
 [ 67  53 100  54]
 [ 85  85  83  53]
 [100  92  78  70]]
English Grades:
 [[92 74 93 77]
 [62 56 75 84]
 [81 99 74 74]
 [63 73 51 89]
 [97 85 60 57]
 [96 97 55 66]]
Shape after swapping terms and subjects: (6, 3, 4)
3rd Student's Science Grades for All Terms: [88 80 83 70]
