In [1]:
import numpy as np

# Step 1: Create two 2D arrays (representing grayscale images)
image1 = np.random.randint(0, 256, (5, 5))  # Image 1: 5x5 pixels
image2 = np.random.randint(0, 256, (5, 5))  # Image 2: 5x5 pixels

print("Image 1 (5x5):\n", image1)
print("\nImage 2 (5x5):\n", image2)

# Step 2: Perform vertical stacking (vstack)
stacked_vertical = np.vstack((image1, image2))  # Resulting shape: (10, 5)
print("\nStacked Image Vertically (10x5):\n", stacked_vertical)

# Step 3: Perform horizontal stacking (hstack)
stacked_horizontal = np.hstack((image1, image2))  # Resulting shape: (5, 10)
print("\nStacked Image Horizontally (5x10):\n", stacked_horizontal)

# Step 4: Split the vertically stacked image into smaller parts
# Splitting it into 2 equal parts along the first axis
split_vertical = np.split(stacked_vertical, 2)

print("\nSplit Vertical Stacked Image into 2 parts:")
for i, part in enumerate(split_vertical):
    print(f"\nPart {i+1} (5x5):\n", part)


Image 1 (5x5):
 [[ 57 230 248  21 102]
 [ 93  19  42 243 122]
 [ 10 187  21  78 111]
 [193  53  65  67  91]
 [ 77 242 214 222 104]]

Image 2 (5x5):
 [[191  63  34 156  48]
 [107  50 206 158  30]
 [ 41  74 227  54  22]
 [247  74  90  93  16]
 [  7 225  94  34 245]]

Stacked Image Vertically (10x5):
 [[ 57 230 248  21 102]
 [ 93  19  42 243 122]
 [ 10 187  21  78 111]
 [193  53  65  67  91]
 [ 77 242 214 222 104]
 [191  63  34 156  48]
 [107  50 206 158  30]
 [ 41  74 227  54  22]
 [247  74  90  93  16]
 [  7 225  94  34 245]]

Stacked Image Horizontally (5x10):
 [[ 57 230 248  21 102 191  63  34 156  48]
 [ 93  19  42 243 122 107  50 206 158  30]
 [ 10 187  21  78 111  41  74 227  54  22]
 [193  53  65  67  91 247  74  90  93  16]
 [ 77 242 214 222 104   7 225  94  34 245]]

Split Vertical Stacked Image into 2 parts:

Part 1 (5x5):
 [[ 57 230 248  21 102]
 [ 93  19  42 243 122]
 [ 10 187  21  78 111]
 [193  53  65  67  91]
 [ 77 242 214 222 104]]

Part 2 (5x5):
 [[191  63  34 156  48]
 